<a href="https://colab.research.google.com/github/PikuSpeaks123/PyTorch/blob/main/1_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [7]:
x_np

tensor([[1, 2],
        [3, 4]])

In [9]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [13]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.5961, 0.9173],
        [0.9776, 0.1124]])

In [15]:
shape = (2,3,)
torch.rand(shape)

tensor([[0.2263, 0.4485, 0.6038],
        [0.9522, 0.7091, 0.4140]])

In [16]:
torch.ones(shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [18]:
torch.zeros(shape, dtype=torch.int)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [19]:
tensor = torch.rand(3,4)
tensor

tensor([[0.3216, 0.6604, 0.6045, 0.9959],
        [0.6165, 0.6890, 0.6487, 0.9187],
        [0.4783, 0.0434, 0.5267, 0.3854]])

In [20]:
tensor.shape

torch.Size([3, 4])

In [21]:
tensor.dtype

torch.float32

In [22]:
tensor.device

device(type='cpu')

In [24]:
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

In [25]:
tensor

tensor([[0.3216, 0.6604, 0.6045, 0.9959],
        [0.6165, 0.6890, 0.6487, 0.9187],
        [0.4783, 0.0434, 0.5267, 0.3854]], device='cuda:0')

In [26]:
tensor = torch.ones(4, 4)

In [27]:
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
tensor[0]

tensor([1., 1., 1., 1.])

In [29]:
tensor[:,0]

tensor([1., 1., 1., 1.])

In [30]:
tensor[:,-1]

tensor([1., 1., 1., 1.])

In [31]:
tensor[:,1]=0

In [32]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [33]:
torch.cat([tensor, tensor, tensor], dim=1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [34]:
tensor @ tensor.T

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [35]:
tensor.matmul(tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [36]:
torch.rand_like(tensor @ tensor.T)

tensor([[0.6133, 0.6614, 0.2652, 0.2323],
        [0.2705, 0.5980, 0.3004, 0.5685],
        [0.4149, 0.0907, 0.6217, 0.6039],
        [0.0596, 0.9233, 0.0734, 0.8053]])

In [37]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [38]:
tensor*tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [44]:
shape = (3,3,)
torch.rand(shape,dtype=torch.float32)

tensor([[0.4004, 0.0538, 0.8091],
        [0.0232, 0.5496, 0.2975],
        [0.1639, 0.9550, 0.3194]])

In [45]:
data = [[1,2],[3,4]]
tensor = torch.tensor(data)
tensor

tensor([[1, 2],
        [3, 4]])

In [46]:
tensor * tensor

tensor([[ 1,  4],
        [ 9, 16]])

In [47]:
tensor.mul(tensor)

tensor([[ 1,  4],
        [ 9, 16]])

In [48]:
tensor

tensor([[1, 2],
        [3, 4]])

In [49]:
tensor @ tensor.T

tensor([[ 5, 11],
        [11, 25]])

In [50]:
tensor.matmul(tensor.T)

tensor([[ 5, 11],
        [11, 25]])

In [52]:
tensor

tensor([[1, 2],
        [3, 4]])

In [51]:
tensor.sum()

tensor(10)

In [53]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

10 <class 'int'>


In [54]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1, 2],
        [3, 4]]) 

tensor([[6, 7],
        [8, 9]])
